version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install

      - run: npm run test
      - run: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js